# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocoder.Address')),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('daily_request_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ApiRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Success'), (2, 'Error')], default=0)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocoder.ApiKey')),
            ],
        ),
        migrations.CreateModel(
            name='GeoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresses', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='apikey',
            name='api_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocoder.ApiProvider'),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocoder.ApiKey'),
        ),
        migrations.AddField(
            model_name='address',
            name='geo_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocoder.GeoRequest'),
        ),
    ]
