# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Success'), (2, 'Error')], default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocoder.Address')),
            ],
            options={
                'verbose_name_plural': 'geo',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('YA', 'Yandex.Maps'), ('GO', 'Google Maps'), ('OS', 'OpenStreetMap')], max_length=2)),
                ('daily_request_limit', models.IntegerField()),
                ('last_request_date', models.DateField(default=datetime.date.today)),
                ('request_count', models.IntegerField(default=0)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addresses', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='geo',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocoder.Provider'),
        ),
        migrations.AddField(
            model_name='address',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocoder.Request'),
        ),
    ]
