# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0002_georequest_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Success'), (2, 'Error')], default=0)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('daily_request_limit', models.IntegerField()),
                ('key', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='GeoRequest',
            new_name='Request',
        ),
        migrations.RemoveField(
            model_name='addressinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='addressinfo',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='api_provider',
        ),
        migrations.RemoveField(
            model_name='apirequest',
            name='api_key',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='geo_request',
            new_name='request',
        ),
        migrations.DeleteModel(
            name='AddressInfo',
        ),
        migrations.DeleteModel(
            name='ApiKey',
        ),
        migrations.DeleteModel(
            name='ApiProvider',
        ),
        migrations.DeleteModel(
            name='ApiRequest',
        ),
        migrations.AddField(
            model_name='geo',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocoder.Address'),
        ),
        migrations.AddField(
            model_name='geo',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocoder.Provider'),
        ),
    ]
