# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0003_auto_20170319_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geo',
            options={'verbose_name_plural': 'geo'},
        ),
        migrations.AlterField(
            model_name='geo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='geo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10),
        ),
    ]
