# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0004_auto_20170319_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='geo',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
