# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0005_auto_20170319_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='name',
        ),
        migrations.AddField(
            model_name='provider',
            name='vendor',
            field=models.CharField(choices=[('YA', 'Yandex.Maps'), ('GO', 'Google Maps'), ('OS', 'OpenStreetMap')], default='YA', max_length=50),
            preserve_default=False,
        ),
    ]
