# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0006_auto_20170319_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='vendor',
            field=models.CharField(choices=[('YA', 'Yandex.Maps'), ('GO', 'Google Maps'), ('OS', 'OpenStreetMap')], max_length=2),
        ),
    ]
